# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78da0b90fa525020de67240f9bbf167d8e766b24536bf9dac44b6ad71aca87664a43075eee0b50f057a90a7356ce0dc3ba312f7a95c2d912f7564339d7420672

test:
  secret_key_base: caea6642c835c135bbd2e36a8d47d5652f52854e0e610405823fa27636b824d143664f70386a5b29b9f3278bbf3340d6441ac1e4bb4b7a1c6ca2d8a3b03b48e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
